language: python
python:
  - "2.7"
install:
  - pip install coveralls
script:
  - python setup.py install
  - coverage run tests/test.py
after_success:
  - coveralls
deploy:
  provider: pypi
  user: dpmcmlxxvi
  password:
    secure: $PYPI_TOKEN
  on:
    tags: true
    repo: dpmcmlxxvi/pixelscan
